jobs:
  - job: GPU
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      - bash: |
          docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
          cd dockerfiles
          make docker_build_gpu
          ./push_gpu.sh
  - job: GPU_Agent
    dependsOn:
      - GPU
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      - bash: |
          docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
          cd tensorrt-agent/dockerfiles
          make docker_build_gpu
          ./push_gpu.sh
  - job: Update_Microbadger
    dependsOn:
      - GPU
    #steps:
    # - script: "curl -X POST https://hooks.microbadger.com/images/carml/tensorrt/BmyRI58bz0gUqFsiFFvhh75QiII="
  - job: Update_Microbadger_Agent
    dependsOn:
      - GPU_Agent
    #steps:
    # - script: "curl -X POST https://hooks.microbadger.com/images/carml/tensorrt-agent/vnfn6OrzhZEARsQy6ltGO45Bfmw="
