jobs:
  - job: GPU
    pool:
      vmImage: "Ubuntu 16.04"
    steps:
      - bash: |
          docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
          cd dockerfiles
          make docker_build_gpu
          while $(make docker_push_gpu); do :; done
  - job: GPU_Agent
    dependsOn:
      - GPU
    pool:
      vmImage: "Ubuntu 16.04"
    steps:
      - bash: |
          docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
          cd caffe-agent/dockerfiles
          make docker_build_gpu
          while $(make docker_push_gpu); do :; done
  - job: Update_Microbadger
    dependsOn:
      - GPU
    steps:
      # - script: "curl -X POST https://hooks.microbadger.com/images/carml/caffe/BmyRI58bz0gUqFsiFFvhh75QiII="
  - job: Update_Microbadger_Agent
    dependsOn:
      - GPU_Agent
    steps:
      # - script: "curl -X POST https://hooks.microbadger.com/images/carml/caffe-agent/vnfn6OrzhZEARsQy6ltGO45Bfmw="